spring: 
  profiles.active: production 

---

spring:
  profiles: dev
  application:
    name: subscription-service
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/adidas
    username: sa
    password: password
    testWhileIdle: true # Keep the connection alive if idle for a long time (needed in production)
    validationQuery: SELECT 1
  jpa:
    show-sql: true # Show or not log for each sql query 
    hibernate:
      ddl-auto: update # Hibernate ddl auto (create, create-drop, update) 
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy 
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect # The SQL dialect makes Hibernate generate better SQL for the chosen database
     
server:
  port: 8401
  
security.oauth2.resource.user-info-uri: http://192.168.99.100:8304/rest/security/user-info

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.99.100:8300/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  hystrix:
    enabled: true

logging:
  level:
    org.springframework.web: ERROR
    com.mantolin: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg [%X{X-B3-TraceId},%X{X-B3-SpanId},%X{X-B3-ParentSpanId},%X{X-Span-Export}]%n"

---

spring:
  profiles: production
  application:
    name: subscription-service
  datasource:
    url: jdbc:mysql://mysql-database:3306/adidas
    username: sa
    password: password
    testWhileIdle: true # Keep the connection alive if idle for a long time (needed in production)
    validationQuery: SELECT 1
  jpa:
    show-sql: true # Show or not log for each sql query 
    hibernate:
      ddl-auto: update # Hibernate ddl auto (create, create-drop, update) 
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy 
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect # The SQL dialect makes Hibernate generate better SQL for the chosen database
 
server:
  port: 8301
  
security.oauth2.resource.user-info-uri: http://security-service:8304/rest/security/user-info

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-service:8300/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  hystrix:
    enabled: true

logging:
  level:
    org.springframework.web: ERROR
    com.mantolin: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg [%X{X-B3-TraceId},%X{X-B3-SpanId},%X{X-B3-ParentSpanId},%X{X-Span-Export}]%n"
 
---

spring:
  profiles: test
  application:
    name: subscription-service
  jpa.properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
  datasource.url: jdbc:h2:mem:test

eureka.client.enabled: false

logging:
  level:
    org.springframework.web: ERROR
    com.mantolin: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

 