spring:
  application:
    name: eureka-service
 
server:
  port: 8300

eureka:
  server:
    enableSelfPreservation: true
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/