spring:
  application:
    name: event-service
 
server:
  port: 8302

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-service:8300/eureka/

logging:
  level:
    org.springframework.web: ERROR
    com.mantolin: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg [%X{X-B3-TraceId},%X{X-B3-SpanId},%X{X-B3-ParentSpanId},%X{X-Span-Export}]%n"